export const jcuken = [
  {
    // left side of the keyboard
    chars: 'ёйфяцычувскамепи',
    signs: '!"№;%:'
  },
  {
    // right side of the keyboard
    chars: 'нртгоьшлбщдюзжхэъ',
    signs: '?*()_+,/'
  },

  // finger pointers
  { pinky: '[ё1!йфя0)зж.,-_хэ=+ъ\\/]' },
  { ring: '[2цыч9(щдю]' },
  { middle: '[3№увс8*шлб]' },
  { lIndex: '[4;кам5%епи6:]' },
  { rIndex: '[7?нртгоь]' },

  { code: 'Backquote', value: 'ё' },
  { code: 'Digit1', value: '!1' },
  { code: 'Digit2', value: '"2' },
  { code: 'Digit3', value: '№3' },
  { code: 'Digit4', value: ';4' },
  { code: 'Digit5', value: '%5' },
  { code: 'Digit6', value: ':6' },
  { code: 'Digit7', value: '?7' },
  { code: 'Digit8', value: '*8' },
  { code: 'Digit9', value: '(9' },
  { code: 'Digit', value: ')0' },
  { code: 'Minus', value: '_-' },
  { code: 'Equal', value: '+=' },
  { code: 'Backspace', value: 'backspace' },

  { code: 'Tab', value: 'tab' },
  { code: 'KeyQ', value: 'й' },
  { code: 'KeyW', value: 'ц' },
  { code: 'KeyE', value: 'у' },
  { code: 'KeyR', value: 'к' },
  { code: 'KeyT', value: 'е' },
  { code: 'KeyY', value: 'н' },
  { code: 'KeyU', value: 'г' },
  { code: 'KeyI', value: 'ш' },
  { code: 'KeyO', value: 'щ' },
  { code: 'KeyP', value: 'з' },
  { code: 'BracketLeft', value: 'х' },
  { code: 'BracketRight', value: 'ъ' },
  { code: 'Backslash', value: '/\\' },

  { code: 'CapsLock', value: 'caps' },
  { code: 'KeyA', value: 'ф' },
  { code: 'KeyS', value: 'ы' },
  { code: 'KeyD', value: 'в' },
  { code: 'KeyF', value: 'а' },
  { code: 'KeyG', value: 'п' },
  { code: 'KeyH', value: 'р' },
  { code: 'KeyJ', value: 'о' },
  { code: 'KeyK', value: 'л' },
  { code: 'KeyL', value: 'д' },
  { code: 'Semicolon', value: 'ж' },
  { code: 'Quote', value: 'э' },
  { code: 'Enter', value: 'enter' },

  { code: 'ShiftLeft', value: 'shift' },
  { code: 'KeyZ', value: 'я' },
  { code: 'KeyX', value: 'ч' },
  { code: 'KeyC', value: 'с' },
  { code: 'KeyV', value: 'м' },
  { code: 'KeyB', value: 'и' },
  { code: 'KeyN', value: 'т' },
  { code: 'KeyM', value: 'ь' },
  { code: 'Comma', value: 'б' },
  { code: 'Period', value: 'ю' },
  { code: 'Slash', value: ',.' },
  { code: 'ShiftRight', value: 'shift' },

  { code: 'ControlLeft', value: 'ctrl' },
  { code: 'MetaLeft', value: 'win' },
  { code: 'AltLeft', value: 'alt' },
  { code: 'Space', value: ' ' },
  { code: 'AltRight', value: 'alt' },
  { code: 'MetaRight', value: 'win' },
  { code: 'ContextMenu', value: 'menu' },
  { code: 'ControlRight', value: 'ctrl' }
]

export const qwerty = [
  {
    // left side of the keyboard
    chars: 'qazwsxedcrfvtgb',
    signs: '~!@#$%^'
  },
  {
    // right side of the keyboard
    chars: 'yhnujmikolp',
    signs: '&*()_+{}|:"<>?'
  },

  // finger pointers
  { pinky: '`~1!qaz0)p;:/?-_[{\'"=+]}\\|' },
  { ring: '2@wsx9(ol.>' },
  { middle: '3#edc8*ik,<' },
  { lIndex: '4$rfv5%tgb6^' },
  { rIndex: '4$rfv5%tgb6^' },

  { code: 'Backquote', value: '~`' },
  { code: 'Digit1', value: '!1' },
  { code: 'Digit2', value: '@2' },
  { code: 'Digit3', value: '#3' },
  { code: 'Digit4', value: '$4' },
  { code: 'Digit5', value: '%5' },
  { code: 'Digit6', value: '^6' },
  { code: 'Digit7', value: '&7' },
  { code: 'Digit8', value: '*8' },
  { code: 'Digit9', value: '(9' },
  { code: 'Digit', value: ')0' },
  { code: 'Minus', value: '_-' },
  { code: 'Equal', value: '+=' },
  { code: 'Backspace', value: 'backspace' },

  { code: 'Tab', value: 'tab' },
  { code: 'KeyQ', value: 'q' },
  { code: 'KeyW', value: 'w' },
  { code: 'KeyE', value: 'e' },
  { code: 'KeyR', value: 'r' },
  { code: 'KeyT', value: 't' },
  { code: 'KeyY', value: 'y' },
  { code: 'KeyU', value: 'u' },
  { code: 'KeyI', value: 'i' },
  { code: 'KeyO', value: 'o' },
  { code: 'KeyP', value: 'p' },
  { code: 'BracketLeft', value: '{' },
  { code: 'BracketRight', value: '}' },
  { code: 'Backslash', value: '|\\' },

  { code: 'CapsLock', value: 'caps' },
  { code: 'KeyA', value: 'a' },
  { code: 'KeyS', value: 's' },
  { code: 'KeyD', value: 'd' },
  { code: 'KeyF', value: 'f' },
  { code: 'KeyG', value: 'g' },
  { code: 'KeyH', value: 'h' },
  { code: 'KeyJ', value: 'j' },
  { code: 'KeyK', value: 'k' },
  { code: 'KeyL', value: 'l' },
  { code: 'Semicolon', value: ':;' },
  { code: 'Quote', value: `"'` },
  { code: 'Enter', value: 'enter' },

  { code: 'ShiftLeft', value: 'shift' },
  { code: 'KeyZ', value: 'z' },
  { code: 'KeyX', value: 'x' },
  { code: 'KeyC', value: 'c' },
  { code: 'KeyV', value: 'v' },
  { code: 'KeyB', value: 'b' },
  { code: 'KeyN', value: 'n' },
  { code: 'KeyM', value: 'm' },
  { code: 'Comma', value: '<,' },
  { code: 'Period', value: '>.' },
  { code: 'Slash', value: '?/' },
  { code: 'ShiftRight', value: 'shift' },

  { code: 'ControlLeft', value: 'ctrl' },
  { code: 'MetaLeft', value: 'win' },
  { code: 'AltLeft', value: 'alt' },
  { code: 'Space', value: ' ' },
  { code: 'AltRight', value: 'alt' },
  { code: 'MetaRight', value: 'win' },
  { code: 'ContextMenu', value: 'menu' },
  { code: 'ControlRight', value: 'ctrl' }
]
